### ISSUE TITLE
Wrong License?

### ISSUE THREAD

**Issue by greggman** [wcchoi/libunrar-js#2]
Unless I'm missing something it seems like you have to GPL this? The project you linked to

https://github.com/seikichi/unrar.js

is GPLed (not LGPLed) so putting that code in this lib requires the same licence. If it was LGPLed you could just use it as a library but it's not LGPLed it's GPLed.

Am I wrong?

**Comment by greggman** [comment]
Oh I see, you didn't use that library? I guess I mis-understood why you linked to it in the read me.

**Comment by wcchoi** [comment]
Yes, unrar.js is just related, I have not used the js code in that library. Though I take a bit of code from that repo's index.html file to use in this project's index.html (which is just an example of how to use the library). So I guess I do not have to release the stuff in GPL.
